Repository sysc3010-t3/CarCamApp, pull requests merged in 2019-12, with the labels that each got.

#9 Integrate user login and registration with server
  CarCamApp.Android/CarCamApp.Android.csproj
  CarCamApp.Android/Properties/AndroidManifest.xml
  CarCamApp/CarCamApp.csproj
  CarCamApp/Messages/Ack.cs
  CarCamApp/Messages/Error.cs
  CarCamApp/Messages/GetCars.cs
  CarCamApp/Messages/GetSSID.cs
  CarCamApp/Messages/Link.cs
  CarCamApp/Messages/Login.cs
  CarCamApp/Messages/Message.cs
  CarCamApp/Messages/Move.cs
  CarCamApp/Messages/RegUser.cs
  CarCamApp/Messages/SetLED.cs
  CarCamApp/Messages/WifiConn.cs
  CarCamApp/Models/Car.cs
  CarCamApp/Models/Constants.cs
  CarCamApp/Models/ServerUnreachableException.cs
  CarCamApp/Models/SocketClient.cs
  CarCamApp/Models/User.cs
  CarCamApp/Views/LoginPage.xaml
  CarCamApp/Views/LoginPage.xaml.cs
  CarCamApp/Views/SignUpPage.xaml
  CarCamApp/Views/SignUpPage.xaml.cs
Labels: enhancement

#10 Integrate car list with server
  .gitignore
  CarCamApp.Android/CarCamApp.Android.csproj
  CarCamApp.Android/Resources/Resource.designer.cs
  CarCamApp.Android/Resources/drawable-hdpi/add.png
  CarCamApp.Android/Resources/drawable-hdpi/log_out.png
  CarCamApp.Android/Resources/drawable-hdpi/sharp_add_black_18.png
  CarCamApp.Android/Resources/drawable-hdpi/sharp_add_black_24.png
  CarCamApp.Android/Resources/drawable-hdpi/sharp_add_black_36.png
  CarCamApp.Android/Resources/drawable-mdpi/sharp_add_black_18.png
  CarCamApp.Android/Resources/drawable-mdpi/sharp_add_black_24.png
  CarCamApp.Android/Resources/drawable-mdpi/sharp_add_black_36.png
  CarCamApp.Android/Resources/drawable-mdpi/sharp_add_black_48.png
  CarCamApp.Android/Resources/drawable-xhdpi/sharp_add_black_18.png
  CarCamApp.Android/Resources/drawable-xhdpi/sharp_add_black_24.png
  CarCamApp.Android/Resources/drawable-xhdpi/sharp_add_black_36.png
  CarCamApp.Android/Resources/drawable-xhdpi/sharp_add_black_48.png
  CarCamApp.Android/Resources/drawable-xxhdpi/sharp_add_black_18.png
  CarCamApp.Android/Resources/drawable-xxhdpi/sharp_add_black_24.png
  CarCamApp.Android/Resources/drawable-xxhdpi/sharp_add_black_36.png
  CarCamApp.Android/Resources/drawable-xxhdpi/sharp_add_black_48.png
  CarCamApp.Android/Resources/drawable-xxxhdpi/sharp_add_black_18.png
  CarCamApp.Android/Resources/drawable-xxxhdpi/sharp_add_black_24.png
  CarCamApp.Android/Resources/drawable-xxxhdpi/sharp_add_black_36.png
  CarCamApp.Android/Resources/drawable-xxxhdpi/sharp_add_black_48.png
  CarCamApp.Android/Resources/drawable/add.xml
  CarCamApp.Android/Resources/drawable/log_out.png
  CarCamApp/CarCamApp.csproj
  CarCamApp/Models/Car.cs
  CarCamApp/Models/Constants.cs
  CarCamApp/Models/User.cs
  CarCamApp/Views/Dashboard.xaml
  CarCamApp/Views/Dashboard.xaml.cs
  CarCamApp/Views/LoginPage.xaml.cs
  CarCamApp/Views/Menu/MasterDetail.xaml
  CarCamApp/Views/Menu/MasterDetail.xaml.cs
  CarCamApp/Views/Menu/MasterDetailDetail.xaml
  CarCamApp/Views/Menu/MasterDetailDetail.xaml.cs
  CarCamApp/Views/Menu/MasterDetailMaster.xaml
  CarCamApp/Views/Menu/MasterDetailMaster.xaml.cs
  CarCamApp/Views/Menu/MasterDetailMasterMenuItem.cs
  CarCamApp/Views/SignUpPage.xaml
  CarCamApp/Views/SignUpPage.xaml.cs
Labels: enhancement

#11 Integrate car selection with server
  CarCamApp/Views/Dashboard.xaml.cs
Labels: enhancement

#12 Add the rest of the app
  CarCamApp.Android/MainActivity.cs
  CarCamApp.Android/Properties/AndroidManifest.xml
  CarCamApp.Android/Resources/values/styles.xml
  CarCamApp/CarCamApp.csproj
  CarCamApp/Messages/Ack.cs
  CarCamApp/Messages/WifiConn.cs
  CarCamApp/Models/Constants.cs
  CarCamApp/Models/WifiNetwork.cs
  CarCamApp/Views/ConnectCar.xaml
  CarCamApp/Views/ConnectCar.xaml.cs
  CarCamApp/Views/Dashboard.xaml.cs
  CarCamApp/Views/RegisterCar.xaml
  CarCamApp/Views/RegisterCar.xaml.cs
  CarCamApp/Views/VideoStreamPage.xaml
  CarCamApp/Views/VideoStreamPage.xaml.cs
Labels: enhancement, help wanted

#13 Add refresh button to Dashboard
  CarCamApp.Android/CarCamApp.Android.csproj
  CarCamApp.Android/MainActivity.cs
  CarCamApp.Android/Properties/AndroidManifest.xml
  CarCamApp.Android/Resources/Resource.designer.cs
  CarCamApp.Android/Resources/drawable-hdpi/refresh.png
  CarCamApp/Models/Constants.cs
  CarCamApp/Views/Dashboard.xaml.cs
  CarCamApp/Views/RegisterCar.xaml.cs
Labels: enhancement

#14 Add a README for the app repo
  README.md
Labels: documentation
